table 単位
	lineageTag: 3e7a729f-fbdf-4ea7-ad36-833f28b0d403

	column 単位
		dataType: string
		lineageTag: 8856e184-e811-4e61-b90d-82a1b3078903
		summarizeBy: none
		sourceColumn: 単位
		sortByColumn: 順番

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 順番
		dataType: int64
		formatString: 0
		lineageTag: af691b1f-151f-4742-be5a-cacc4afe8183
		summarizeBy: sum
		sourceColumn: 順番

		annotation SummarizationSetBy = Automatic

	partition 単位-873ff651-4755-4438-ae45-0a961ca34212 = m
		mode: import
		source =
				let
				    ソース = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wetrb/LStTUlHyVgpVida6fnMfU92tENEjMAiT1taIFxDCBfMNlGKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [単位 = _t, 順番 = _t]),
				    変更された型 = Table.TransformColumnTypes(ソース,{{"単位", type text}, {"順番", Int64.Type}})
				in
				    変更された型

	annotation PBI_ResultType = Table

